### ISSUE TITLE
"ReferenceError: google is not defined"

### ISSUE THREAD

**Issue by digitaledge** [danielehrhardt/Ionic-2-Google-Maps-Marker-Cluster#1]
Hi, this looks really interesting, but when running your code i am getting a "ReferenceError: google is not defined"...   Which maps plugin did you use? Could you maybe add some infos how to get it to run?

**Comment by danielehrhardt** [comment]
I check that later. Thank you for opening the issue.

**Comment by mrtn3000** [comment]
I got this error when trying to run it on a device. Seems like on a device the scripts are not properly loaded. Changed [this line](https://github.com/danielehrhardt/Ionic-2-Google-Maps-Marker-Cluster/blob/master/src/index.html#L38) to start with `https://`instead of `//` otherwise it tries to load the maps script from `file://`.

**Comment by danielehrhardt** [comment]
@mrtn3000 yes i forgot that thank you i fixed that
